In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.cross_decomposition import PLSCla
from sklearn.model_selection import train_test_split

In [4]:
# load data
lsp = pd.read_csv('data/clusters_LSP.csv')
rmse = pd.read_csv('data/rmse_random.csv')
dem = pd.read_csv('data/dem_random.csv')
pft = pd.read_csv('data/clusters_PFT.csv')

In [5]:
 # take random samples on lsp
lsp = lsp.sample(n=5000, random_state=1)
pft = pft.sample(n=5000, random_state=1)
lsp.head()

,cluster,sos,pos,eos,vsos,vpos,veos,los,msp,mau,vmsp,vmau,ampl,ios,rog,ros,sw
941372,3.0,223.0,322.0,343.0,0.422011,0.650248,0.624166,120.0,273.0,329.0,0.485281,0.617068,0.783603,56.651338,0.002305,-0.001242,0.396496
644778,2.0,117.0,174.0,273.0,0.812245,1.528975,1.156799,156.0,146.0,223.0,1.420542,1.221612,1.949521,187.800350,0.012574,-0.003759,0.018752
1673330,5.0,75.0,188.0,280.0,0.827766,1.063637,0.763672,205.0,132.0,237.0,0.839417,0.877791,0.669038,176.382537,0.002087,-0.003260,0.069778
1505413,6.0,40.0,103.0,223.0,0.444023,1.042216,0.582846,183.0,68.0,160.0,0.387295,0.817712,0.905521,118.222153,0.009495,-0.003828,0.127192
1643991,7.0,5.0,5.0,188.0,1.255410,1.255410,0.770075,183.0,5.0,96.0,1.255410,0.909539,0.891462,148.974543,NaN,-0.002652,-0.254190

         cluster  PFT
941372       2.0  5.0
644778       4.0  6.0
1673330      1.0  5.0
1505413      1.0  5.0
1643991      1.0  1.0
...          ...  ...
907011       2.0  5.0
954452       1.0  5.0
1288414      1.0  5.0
111585       4.0  5.0
12341        3.0  1.0

[5000 rows x 2 columns]